#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+

if [[ -z $2 ]]; then
	echo "Usage: for-each-commit <base commit> <command ...>" >&2
	echo ""
	echo "eg. for-each-commit origin/master \"git checkout \\\$sha && make\""
	exit 1
fi

base=$1
shift

orig_branch=$(git symbolic-ref --short HEAD)

for sha in $(git rev-list --reverse ${base}..HEAD)
do
    echo "Executing '$@' for sha $sha"
    eval $@

    if [[ $? -ne 0 ]]; then
	echo "Error: command '$@' failed for:" >&2
	echo "       $(git log -1 --oneline $sha)" >&2
	echo "       NOT switching back to branch $orig_branch" >&2
	exit 1
    fi
done

echo "All OK"

curr_branch=$(git symbolic-ref --short HEAD 2>/dev/null)
if [[ $curr_branch != $orig_branch ]]; then
    echo "Switching back to $orig_branch ..."
    git checkout $orig_branch
fi

exit $?
